### ISSUE TITLE
/recent days 1 is not working

### ISSUE THREAD

**Issue by snudel** [B-2U/ISAC#3]
Hi
The bot stopped accepting 1 as a parameter for the /recent command.
As this is the default value, the usage got a little clunky.

Did the api change or should the default be set to 2?
Or am I doing something wrong?

After all, a great bot. thanks for the effort already.

MIchael

**Comment by B-2U** [comment]
can you provide the detail of the problem?
whats ur input
what bot replied
and your game server(Na EU etc)
thx

**Comment by snudel** [comment]
Usually, I just typed /recent and it spit out the results for this day.
Now if i type /recent, the reply is:
snudel played 0 battle in last 1 day. 
Choose a larger day number?
The I manually need to say 2 or more days.

But i did play games already.

**Comment by B-2U** [comment]
a new day for the bot start at as the daily mission reset time of the game server, 
so for EU its like 5:00 UTC, I think that's why it happened.
